const assert=require('node:assert/strict');
const {readinessOf,snapshotAge,ticketMatches,filterServices}=require('../web/catalog.js');
const ready={state:'opened',draft:false,pipeline:'success',approval:{status:'approved'},merge:'mergeable'};
assert.equal(readinessOf(ready),'ready');
for(const pipeline of ['stale','unknown','skipped',''])assert.equal(readinessOf({...ready,pipeline}),'unknown');
for(const pipeline of ['failed','canceled','pending','manual','running'])assert.equal(readinessOf({...ready,pipeline}),'blocked');
assert.equal(readinessOf({...ready,approval:{status:'unknown'}}),'unknown');
assert.equal(readinessOf({...ready,approval:{status:'waiting'}}),'blocked');
assert.equal(readinessOf({...ready,approval:{status:'not-required'}}),'ready');
for(const merge of ['not_mergeable','checking','unchecked',''])assert.equal(readinessOf({...ready,merge}),'unknown');
assert.equal(readinessOf({...ready,draft:true}),'blocked');
assert.equal(readinessOf({...ready,state:'closed'}),'blocked');
assert.equal(readinessOf(null),'unknown');
assert.equal(snapshotAge('bad'),Infinity);
assert.equal(snapshotAge('2026-10-07T01:00:00Z',Date.parse('2026-10-07T00:00:00Z')),Infinity);
assert.equal(snapshotAge('2026-10-07T00:00:00Z',Date.parse('2026-10-07T00:06:00Z')),360000);
assert(ticketMatches('feature/pay-123-update','PAY-123'));
assert(!ticketMatches('feature/PAY-1234','PAY-123'));
assert(!ticketMatches('NOTPAY-123','PAY-123'));
assert(ticketMatches('fix [PAY-123]','PAY-123'));
assert(ticketMatches('x/a.b+123','a.b+123'));
const services=[{service:'Billing',name:'billing-api',owner:'Payments',system:'Checkout',path:'C:/fixtures/billing',kind:'service'},{service:'Library',owner:'Platform',kind:'library'}];
assert.deepEqual(filterServices(services,'payments billing'),[services[0]]);
assert.deepEqual(filterServices(services,'','library'),[services[1]]);
assert.deepEqual(filterServices(services,'missing'),[]);
console.log('PASS: readiness never infers approval or current CI, stale controller age, ticket boundaries and catalog search');
