const assert=require('node:assert/strict');
const fs=require('node:fs');
const C=require('../web/cockpit.js');
assert.deepEqual(C.primaryViews,['fleet','my-work','focus-inbox','catalog']);
for(const term of ['all repos','ALL REPOSITORIES','repository health','repos','all-repos'])assert(C.toolMatches('fleet','All repositories',term));
assert(!C.toolMatches('my-work','My work','all repos'));assert(!C.toolMatches('fleet','All repositories','not-a-tool'));assert(C.toolMatches('fleet','All repositories',''));
assert(C.ticketKey('PAY-123'));assert(!C.ticketKey('PAY-123 secret'));assert(!C.ticketKey('--switch'));
assert.equal(C.providerRef({name:'origin/feature/PAY-123',remote:true}),'feature/PAY-123');
assert.equal(C.providerRef({name:'feature/PAY-123',remote:false}),'feature/PAY-123');
assert(C.matches('feature/PAY-123','PAY-123'));assert(!C.matches('feature/PAY-1234','PAY-123'));assert(!C.matches('NOTPAY-123','PAY-123'));
const fresh=[{path:'C:\\SCB\\new-clone',pending:true},{path:'C:\\SCB2\\other'}];
assert.equal(C.scopedServices(fresh,'all').length,2);
assert.deepEqual(C.scopedServices(fresh,'C:\\SCB'),[fresh[0]]);
assert.deepEqual(C.scopedServices(fresh,'C:/SCB/new-clone/'),[fresh[0]]);
assert.deepEqual(C.scopedServices(fresh,'set:Today',[{name:'Today',paths:['c:\\scb\\NEW-clone']}]),[fresh[0]]);
assert.equal(C.attention({changed:3,conflicts:1}).tab,'conflicts');assert.equal(C.attention({ahead:2}).rank,3);assert.equal(C.attention(null).label,'Status unknown');
const services=[{path:'A',dependencies:['c']},{path:'B',dependencies:['a'],owner:'Team B'},{path:'C',dependencies:['b']},{path:'D',dependencies:['B']}];
assert.deepEqual(C.impact(services,'a').map(item=>[item.path,item.depth]),[['B',1],['C',2],['D',2]]);
const now=Date.parse('2026-10-07T10:00:00Z'),sha='a'.repeat(40),branch={sha};
assert.equal(C.remoteAttention({head:sha},{ci:{sha,status:'failed',ref:'main'}}).tab,'failure-lens');
assert.equal(C.remoteAttention({head:sha},{ci:{sha:'b'.repeat(40),status:'failed'}}),null);
assert.equal(C.remoteAttention({head:sha},{mrs:[{sha,approval:{status:'waiting'}}]}).label,'Review pending');
assert.equal(C.proof(branch,[],{sha:'b'.repeat(40),status:'success'},null,now).build,'Unknown');
assert.equal(C.proof(branch,[],{sha,status:'success'},null,now).build,'Passed');
assert.equal(C.proof(branch,[{sha,approval:{status:'unknown'}}],null,null,now).review,'Unknown');
assert.equal(C.proof(branch,[{sha,approval:{status:'approved'}}],null,null,now).review,'Approved at check');
assert.equal(C.proof(branch,[],null,{revision:sha,reconciledAt:'2026-10-07T09:59:00Z'},now).environment,'Source revision observed');
assert.equal(C.proof(branch,[],null,{revision:sha,reconciledAt:'2026-10-08T09:59:00Z'},now).environment,'Stale / unknown');
assert.equal(C.proof(branch,[],null,{revision:'v1',reconciledAt:'2026-10-07T09:59:00Z'},now).environment,'Source linkage unknown');
assert.equal(C.safeUrl('javascript:alert(1)'),'');assert.equal(C.safeUrl('https://user:secret@host.test'),'');assert.equal(C.safeUrl('https://host.test?token=x'),'');assert(C.safeUrl('https://host.test/jobs/12'));
const source=fs.readFileSync(require.resolve('../web/cockpit.js'),'utf8');
const modern=fs.readFileSync(require.resolve('../web/modern.js'),'utf8'),css=fs.readFileSync(require.resolve('../web/cockpit.css'),'utf8');
assert.match(modern,/'all-repos':\(\)=>\{if\(typeof showOperationsCenter==='function'\)showOperationsCenter\('fleet'\)/);
assert.match(css,/#fleet-table \.fleet-head \{ top:0; \}/);assert.match(css,/#fleet-table \{ overflow:auto; \}/);
assert.match(source,/active\?\.hidden&&search\?\.value/);assert.match(source,/setAttribute\('aria-current','page'\)/);
assert.match(source,/request!==serial/);assert.match(source,/expectedUpdatedAt/);assert.match(source,/No logs, file contents, credentials/);
assert(!source.includes("action('create-mr'"));assert(!source.includes("action('push'"));
console.log('PASS: ticket boundaries, action priority, cyclic impact, source SHA proof, safe links, explicit writes and stale-result guards');
