const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../web/app.js'),'utf8');
const copied=[];
const context={state:{workspaceRepo:{path:'C:\\Repos\\demo'}},copyRepositoryValue:(value)=>copied.push(value),refMenuButton:(items)=>({items}),showContextMenu:(event,items)=>context.menu=items};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function repositoryTabContextItems('),source.indexOf('function workingFileContextItems(')),context);
assert.equal(context.fileFullPath({path:'C:/Repos/demo/'},'src/file name.txt'),'C:\\Repos\\demo\\src\\file name.txt');
assert.equal(context.fileFullPath({path:'\\\\server\\share\\repo'},'src/.env.example'),'\\\\server\\share\\repo\\src\\.env.example');
assert.equal(context.fileFullPath({path:'/repos/demo/'},'src/name.txt'),'/repos/demo/src/name.txt');
const file={path:'src/file name.txt'},repo={path:'C:\\Repos\\original'};
const items=context.filePathContextItems(file,repo);
context.state.workspaceRepo={path:'C:\\Repos\\another'};
items[0].run();items[1].run();
assert.deepEqual(copied,['src/file name.txt','C:\\Repos\\original\\src\\file name.txt']);
assert.equal(context.filePathContextItems(file,{})[1].disabled,true);
const row={addEventListener:(name,fn)=>row[name]=fn},button={},tools={replaceChildren:child=>tools.child=child};
context.attachCommitFileMenu(row,button,file,repo,{},tools);
row.contextmenu({});
assert.equal(context.menu[0].label,'Copy relative path');
assert.equal(context.menu[1].label,'Copy full path');
assert.equal(tools.child.items()[1].hint,'C:\\Repos\\original\\src\\file name.txt');
assert(button.title.includes('C:\\Repos\\original\\src\\file name.txt'));
assert(source.includes('attachCommitFileMenu(row,button,file,repo,diff,tools);row.append'));
assert(source.includes('...filePathContextItems(file),'));
console.log('PASS: file right-click and overflow menus, relative/full paths, spaces, UNC, missing root and repository isolation');
const actions=[];context.isFavorite=()=>false;context.repoKey=r=>r.path;
context.run=(action,repo)=>actions.push([action,repo.path]);context.showRepositoryDetails=repo=>actions.push(['details',repo.path]);
context.state.meta={favorites:{}};context.saveMeta=()=>{};context.renderRepoTabs=()=>{};
const tabs=context.repositoryTabContextItems({...repo,valid:true},()=>actions.push(['close',repo.path]));
tabs.find(i=>i.label==='Open in Explorer').run();tabs.find(i=>i.label==='Open in Terminal').run();tabs.find(i=>i.label==='Repository details…').run();tabs.find(i=>i.label==='Close tab').run();
assert(actions.every(a=>a[1]===repo.path),'Tab actions use clicked repository, not active repository');
tabs.find(i=>i.label==='Pin repository').run();assert.equal(context.state.meta.favorites[repo.path],true);
const refs=context.branchCopyContextItems({name:'origin/feature/test'},'remote');refs[0].run();refs[1].run();
assert.deepEqual(copied.slice(-2),['feature/test','origin/feature/test']);
assert.equal(context.branchCopyContextItems({name:'feature/test'},'local').length,1);
const label={setAttribute(){},addEventListener:(name,fn)=>label[name]=fn};
context.bindDiffPathMenu(label,file.path,repo);context.state.workspaceRepo={path:'D:/other'};label.contextmenu({});context.menu[1].run();
assert.equal(copied.at(-1),'C:\\Repos\\original\\src\\file name.txt');
assert(label.title.includes('Right-click'));
console.log('PASS: tab actions, pin, close, branch names/full refs and diff header repository isolation');
