const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../web/app.js'),'utf8');
const pending=[],shown=[];
const node=(tag,cls,text)=>({tag,text,children:[],append(...n){this.children.push(...n)},addEventListener(){},setAttribute(){},classList:{add(){},remove(){}}});
const context={WeakMap,URLSearchParams,state:{workspaceRepo:{path:'fixture'}},encodeURIComponent,el:node,api:url=>new Promise((resolve,reject)=>pending.push({url,resolve,reject})),document:{querySelectorAll:()=>[],createElement:node},workspaceEmpty:node,initializeCommitDetailResizer(){},createDiffViewer:(diff,title)=>({title})};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('const historyReadTokens='),source.indexOf('function createCommitListHeader(')),context);
(async()=>{
 const titleIn=n=>n?.tag==='h3'?n.text:(n?.children||[]).map(titleIn).find(Boolean);
 const pane={isConnected:true,replaceChildren(...items){const title=titleIn(items[0]);if(title)shown.push(title);if(items[0]?.title)shown.push(items[0].title);}};
 const item=hash=>({commit:{subject:hash,hash,fullHash:hash,files:[]}});
 let a=context.loadCommitDetail({fullHash:'A'},pane,node()),b=context.loadCommitDetail({fullHash:'B'},pane,node());
 pending[1].resolve(item('B'));await b;pending[0].resolve(item('A'));await a;assert.deepEqual(shown,['B']);
 a=context.loadCommitDiff({fullHash:'A'},{path:'old'},pane);b=context.loadCommitDiff({fullHash:'A'},{path:'new'},pane);
 pending[3].resolve({result:{diff:'new'}});await b;pending[2].reject(Error('late error'));await a;assert.deepEqual(shown,['B','new']);
 a=context.loadCommitDetail({fullHash:'A'},pane,node());context.state.workspaceRepo.path='other';pending[4].resolve(item('A'));await a;assert.deepEqual(shown,['B','new']);
 context.state.workspaceRepo.path='fixture';a=context.loadCommitDiff({fullHash:'A'},{path:'detached'},pane);pane.isConnected=false;pending[5].resolve({result:{diff:'x'}});await a;assert.deepEqual(shown,['B','new']);
 console.log('PASS: commit and diff latest-wins, stale errors, repo changes and detached panes');
 const requests=[],saved=[];
 Object.assign(context,{content:{querySelector(){return null}},position:{value:{},save(update){Object.assign(this.value,update)}},renderWorkbenchTree(){},scope:{value:'all'},remote:{checked:true},order:{value:'topo'},list:{isConnected:true,scrollTop:42,replaceChildren(){},classList:{toggle(){}}},detail:{replaceChildren(){}},more:{},findAll:{},searchMode:{options:[{},{}]},allSearch:{},clearAll:{},jump:{},selectedCommits:new Set(),updateMulti(){},pageStatus:{},search:{},heading:{text:{querySelector:()=>({})}},data:{branch:'main'},saveMeta(){saved.push(JSON.parse(JSON.stringify(context.state.meta.historyViews)))},draw(){},setNotice(){},api:url=>new Promise(resolve=>requests.push({url,resolve}))});context.state.meta={historyViews:{}};
 vm.runInContext("let historyRequest=0,nextSkip=0,hasMore=false,history=[],loading=false,fullQuery='';const historyRepo='fixture',viewKey='fixture';"+source.slice(source.indexOf('  const load=async(append=false)=>'),source.indexOf('  more.onclick=()=>load(true)'))+';globalThis.loadHistory=load;',context);
 a=context.loadHistory();context.order.value='date';b=context.loadHistory();requests[1].resolve({history:[{fullHash:'new'}],nextSkip:250,hasMore:true});await b;requests[0].resolve({history:[{fullHash:'old'}],nextSkip:250,hasMore:true});await a;
 assert.equal(saved.length,1);assert.equal(saved[0].fixture.order,'date');
 let detailCleared=false,retained=false;context.detail.replaceChildren=()=>{detailCleared=true};context.draw=preserve=>{retained=preserve===true};context.list.scrollTop=73;context.list.scrollLeft=21;
 a=context.loadHistory(true);assert(new URL('http://local'+requests[2].url).searchParams.get('skip')==='250');requests[2].resolve({history:[{fullHash:'new'},{fullHash:'older'}],nextSkip:500,hasMore:false});await a;
 assert.equal(detailCleared,false);assert.equal(retained,true);assert.equal(context.list.scrollTop,73);assert.equal(context.list.scrollLeft,21);
 assert.equal(vm.runInContext('history.length',context),2);assert.equal(context.more.disabled,true);
 console.log('PASS: filter latest-wins, immutable saved order, pagination offset and deduplication');
})().catch(error=>{console.error(error);process.exitCode=1});
