const assert=require('node:assert/strict');
const tools=require('../web/release-tools.js');
assert.equal(tools.githubProject('git@github.com:Wariddon/git-deck.git'),'https://github.com/Wariddon/git-deck');
assert.equal(tools.githubProject('https://github.com/Wariddon/git-deck.git'),'https://github.com/Wariddon/git-deck');
assert.equal(tools.githubProject('https://github.com.evil.test/a/b.git'),null);
assert.equal(tools.githubProject('https://gitlab.com/a/b.git'),null);
const values=new Map();const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};
assert.equal(tools.write(storage,'test',{tab:'history'}),true);
assert.deepEqual(tools.read(storage,'test',{}),{tab:'history'});
storage.setItem('broken','{');assert.deepEqual(tools.read(storage,'broken',{}),{});
const report=tools.report({gitAvailable:true,gitVersion:'git version 2.50.0.windows.1',powerShellVersion:'5.1.123.456',url:'https://secret:token@private.example',path:'C:\\private',error:'secret',user:'private'});
assert(!/secret|token|private/.test(report));assert(JSON.parse(report).gitAvailable);
assert.equal(JSON.parse(tools.report({gitVersion:'secret',powerShellVersion:'private'})).gitVersion,'unknown');
console.log('PASS: persistence, malformed storage, diagnostic allowlist');
const fs=require('node:fs');
const ui=fs.readFileSync(require('node:path').join(__dirname,'../web/release-ui.js'),'utf8');
const push=ui.slice(ui.indexOf("$('push-form').addEventListener('submit'"),ui.indexOf('const readinessTimer'));
assert(push.includes('inlinePushReview()'));
assert(!push.includes('releaseDialog('));
assert(push.includes('version!==pushReviewVersion'));
assert(push.includes("confirm.type='button'"));
assert(push.includes('signature!==pushSignature()'));
console.log('PASS: inline push review, stale-review guard, explicit confirmation control');
const vm=require('node:vm');
const helpers=ui.slice(ui.indexOf('function fileRisk('),ui.indexOf('const baseChangesView='));
const context={};vm.createContext(context);vm.runInContext(helpers,context);
for(const path of ['.env','src/.env.local','keys/private.pem','C:\\demo\\.idea\\workspace.xml','demo.iml'])assert(context.fileRisk(path),path);
for(const path of ['src/app.js','README.md','src/environment.js'])assert(!context.fileRisk(path),path);
assert.equal(context.changeKind('??'),'new');assert.equal(context.changeKind(' M'),'modified');assert.equal(context.changeKind(' D'),'deleted');assert.equal(context.changeKind('UU'),'conflict');
console.log('PASS: sensitive-file heuristics and status filters');
