// Run explicitly with playwright-cli run-code. Only the disposable fixture app is allowed.
async page => {
  if(!page.url().startsWith('http://127.0.0.1:8788/'))throw new Error('QA must use the isolated fixture server');
  await page.setViewportSize({width:1440,height:900});
  let environmentReads=0;
  await page.route('**/api/repo/observed-env?*',async route=>{environmentReads++;await route.fulfill({json:{observed:{env:'uat',app:'billing-uat',source:'Argo CD',sync:'Synced',health:'Healthy',revision:'fixture-revision-123',images:['registry.example.test/billing:1.2.3'],reconciledAt:new Date().toISOString(),checkedAt:new Date().toISOString()}}});});
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.getByRole('button',{name:'Service catalog',exact:true}).click();
  await page.getByText('3 of 3 services',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Repository health',exact:true}).focus();await page.keyboard.press('ArrowDown');
  if(await page.evaluate(()=>document.activeElement.dataset.operationsView)!=='catalog')throw new Error('Keyboard navigation differs from visible tool order');
  const tools=page.getByRole('searchbox',{name:'Find dashboard tool'});await tools.fill('catalog');await tools.press('Enter');await tools.fill('');
  const search=page.getByRole('searchbox',{name:'Find service, owner or system'});
  await search.fill('Payments billing');await page.getByText('1 of 3 services',{exact:true}).waitFor();await search.fill('');
  await page.locator('.catalog-list .catalog-name').filter({hasText:'billing-api-with-long-service-name'}).click();
  if(environmentReads)throw new Error('Environment was read without user action');
  await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async value=>{window.fixtureCopiedPath=value;}}));
  await page.getByRole('button',{name:'Copy repository path',exact:true}).click();
  const copiedPath=await page.evaluate(()=>window.fixtureCopiedPath);
  if(!copiedPath?.endsWith('billing-api-with-long-service-name'))throw new Error('Repository path copy used the wrong service');
  await page.getByRole('button',{name:'Check environment',exact:true}).click();await page.getByText('Health: Healthy · Sync: Synced',{exact:true}).waitFor();
  if(environmentReads!==1)throw new Error('Unexpected environment read count');
  await page.getByRole('button',{name:'Edit metadata',exact:true}).click();
  await page.getByRole('textbox',{name:'Owner',exact:true}).fill('Payments Experience');
  await page.evaluate(()=>{window.fixtureConfirmMessages=[];window.confirm=message=>{window.fixtureConfirmMessages.push(message);return false;};});
  await page.getByRole('button',{name:'Refresh catalog',exact:true}).click();
  if(await page.getByRole('textbox',{name:'Owner',exact:true}).inputValue()!=='Payments Experience')throw new Error('Refresh lost unsaved edits');
  await page.locator('.catalog-list .catalog-name').filter({hasText:'shared-payments-library'}).click();
  if(await page.getByRole('textbox',{name:'Owner',exact:true}).inputValue()!=='Payments Experience')throw new Error('Selection lost unsaved edits');
  if((await page.evaluate(()=>window.fixtureConfirmMessages)).length!==2)throw new Error('Unsaved edit confirmations missing');
  await page.getByRole('button',{name:'Save metadata',exact:true}).click();
  await page.getByRole('button',{name:'Edit metadata',exact:true}).waitFor();
  const catalog=await page.request.get('http://127.0.0.1:8788/api/catalog');const data=await catalog.json();
  if(data.services[0].owner!=='Payments Experience'||data.services[0].environments.length!==1||data.services[0].dependencies.length!==1)throw new Error('Metadata save lost fields');
  await page.getByRole('button',{name:'Check environment',exact:true}).click();await page.getByText('Health: Healthy · Sync: Synced',{exact:true}).waitFor();
  await page.screenshot({path:'output/playwright/06-catalog-desktop.png'});
  await page.setViewportSize({width:1024,height:768});
  await page.screenshot({path:'output/playwright/07-catalog-compact.png'});
  await page.evaluate(()=>GitDeckAppearance.setTextSize(16));
  await page.setViewportSize({width:700,height:800});
  const selector=page.getByRole('combobox',{name:'Dashboard view'});await selector.selectOption('catalog');
  await page.screenshot({path:'output/playwright/08-catalog-large-text.png'});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  if(overflow)throw new Error('Page has horizontal overflow');
  await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>GitDeckAppearance.setTextSize(13));
  await page.getByRole('button',{name:'Merge requests',exact:true}).click();
  await page.getByText('Create merge requests for one branch in many repositories',{exact:true}).click();
  await page.evaluate(()=>state.repos.forEach(repo=>repo.remote='https://gitlab.example.test/fixtures/'+repo.name+'.git'));
  await page.route('**/api/repo/find-branch?*',route=>route.fulfill({json:{branch:{local:true,remote:true,dirty:false}}}));
  const source=page.getByRole('searchbox',{name:'Source branch, for example feature/PAY-1234'});
  await source.fill('feature/PAY-123');await page.getByRole('button',{name:'Find repositories',exact:true}).click();
  await page.getByRole('button',{name:'Create merge requests',exact:true}).waitFor();
  if(await page.getByRole('button',{name:'Create merge requests',exact:true}).isDisabled())throw new Error('Fixture MR plan did not complete');
  await source.fill('feature/PAY-999');
  if(!await page.getByRole('button',{name:'Create merge requests',exact:true}).isDisabled())throw new Error('Changed source branch left an old MR plan executable');
  await page.getByRole('button',{name:'Ticket',exact:true}).click();
  await page.getByRole('searchbox',{name:'Ticket key, for example PAY-1234'}).fill('PAY-123');
  await page.getByRole('button',{name:'Find',exact:true}).click();await page.getByText('3 repositories · 3 commits · 3 not pushed yet',{exact:true}).waitFor();
  await page.getByRole('searchbox',{name:'Ticket key, for example PAY-1234'}).fill('PAY-999');
  if(!await page.getByRole('button',{name:'Copy as Markdown',exact:true}).isDisabled())throw new Error('Old ticket result remains copyable under a new key');
  let mrReads=0;let approval='approved';
  await page.route('**/api/repo/mrs?*',route=>route.fulfill({json:{mergeRequests:[{iid:12,title:'PAY-123: fixture request',source:'feature/PAY-123',target:'main'}]}}));
  await page.route('**/api/repo/mr-readiness?*',route=>{mrReads++;return route.fulfill({json:{readiness:{iid:12,state:'opened',draft:false,pipeline:'success',approval:{status:approval,required:1,left:0},merge:'mergeable',checkedAt:new Date().toISOString()}}});});
  await page.getByRole('searchbox',{name:'Ticket key, for example PAY-1234'}).fill('PAY-123');
  await page.getByRole('button',{name:'Find',exact:true}).click();await page.getByText('3 repositories · 3 commits · 3 not pushed yet',{exact:true}).waitFor();
  if(mrReads)throw new Error('Readiness was requested without a user click');
  await page.getByRole('button',{name:'Check MR readiness',exact:true}).first().click();await page.getByText('Ready at last check',{exact:true}).waitFor();
  approval='unknown';await page.getByRole('button',{name:'Check MR readiness',exact:true}).first().click();await page.getByText('Readiness unknown',{exact:true}).waitFor();
  if(await page.getByText('Ready at last check',{exact:true}).count())throw new Error('Old ready state survives unknown approval');
  await page.getByRole('button',{name:'Service catalog',exact:true}).click();
  await page.route('**/api/repo/observed-env?*',route=>route.fulfill({status:503,json:{error:'Fixture CLI permission denied'}}));
  await page.getByRole('button',{name:'Check environment',exact:true}).click();await page.getByText(/Environment unknown:.*Fixture CLI permission denied/).waitFor();
  if(await page.getByText('Health: Healthy · Sync: Synced',{exact:true}).count())throw new Error('Old healthy state survives a failed check');
  return {services:data.services.length,environmentReads,mrReads,metadataSaved:true,unsavedEditGuard:true,pathCopy:true,bulkMrPlanGuard:true,search:true,responsive:true,ticketCopyGuard:true,unknownStates:true,environment:'MOCK controller and GitLab responses; no external systems contacted'};
}
