'use strict';
// Workbench + ticket evidence. Local reads first; remote calls require an explicit click.
(function(){
  const keyOf=value=>String(value||'').trim().toLowerCase();
  const providerRef=branch=>branch?.remote?branch.name.slice(branch.name.indexOf('/')+1):branch?.name||'';
  const primaryViews=['fleet','pending','my-work','focus-inbox','catalog'];
  function toolMatches(id,label,term){
    const aliases={fleet:'all repos all repositories repository dashboard repository health repos repositories',pending:'pending work unfinished work'};
    const words=keyOf(term).replace(/[-_]+/g,' ').split(/\s+/).filter(Boolean);
    const text=keyOf(label+' '+(aliases[id]||'')).replace(/[-_]+/g,' ');
    return words.every(word=>text.includes(word));
  }
  const ticketKey=value=>/^[A-Z][A-Z0-9]{1,9}-[0-9]{1,12}$/.test(String(value||''));
  function matches(value,key){const escaped=String(key).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return Boolean(key)&&new RegExp('(^|[^A-Z0-9])'+escaped+'(?![A-Z0-9])','i').test(String(value||''));}
  function attention(snapshot){
    if(!snapshot)return {rank:0,label:'Status unknown',tab:'history'};
    if(snapshot.conflicts||snapshot.operation)return {rank:1,label:'Resolve '+(snapshot.operation||'conflicts'),tab:'conflicts'};
    if(snapshot.changed)return {rank:2,label:snapshot.changed+' local changes',tab:'changes'};
    if(snapshot.ahead)return {rank:3,label:snapshot.ahead+' unpushed commits',tab:'history'};
    if(snapshot.behind)return {rank:4,label:snapshot.behind+' incoming commits',tab:'history'};
    return {rank:5,label:'No local action needed',tab:'history'};
  }
  function remoteAttention(snapshot,record){
    if(!snapshot?.head||!record)return null;
    if(record.ci?.sha===snapshot.head&&['failed','canceled'].includes(record.ci.status))return {rank:1,label:'Inspect failed CI',tab:'failure-lens',ref:record.ci.ref};
    if((record.mrs||[]).some(mr=>mr.sha===snapshot.head&&(mr.draft||mr.approval?.status==='waiting')))return {rank:3,label:'Review pending',tab:'my-work'};
    return null;
  }
  function impact(services,path){
    const seen=new Set([keyOf(path)]),queue=[{path,depth:0}],found=[];
    while(queue.length){const current=queue.shift();for(const service of services){if(seen.has(keyOf(service.path)))continue;if((service.dependencies||[]).some(dep=>keyOf(dep)===keyOf(current.path))){seen.add(keyOf(service.path));const item={...service,depth:current.depth+1,via:current.path,evidence:'Declared in local catalog'};found.push(item);queue.push(item);}}}
    return found;
  }
  function proof(branch,mrs,ci,observed,now=Date.now()){
    const sha=branch?.sha||'';
    const currentMrs=(mrs||[]).filter(mr=>mr.sha===sha&&sha);
    const review=!currentMrs.length?'Unknown':currentMrs.some(mr=>mr.draft||mr.approval?.status==='waiting')?'Pending':currentMrs.every(mr=>['approved','not-required'].includes(mr.approval?.status))?'Approved at check':'Unknown';
    const pipeline=ci?.sha===sha&&sha?ci.status:'unknown';
    const time=Date.parse(observed?.reconciledAt||'');const fresh=Number.isFinite(time)&&time<=now+60000&&now-time<=300000;
    const revisions=[observed?.revision,...(observed?.revisions||[])];
    // A controller revision matches source only when the exact full SHA is present. Tags aren't proof.
    const environment=!observed?'Unknown':!fresh?'Stale / unknown':revisions.includes(sha)&&sha?'Source revision observed':'Source linkage unknown';
    return {review,build:pipeline==='success'?'Passed':pipeline==='failed'?'Failed':pipeline==='unknown'?'Unknown':pipeline,environment,image:'Build-to-image linkage unknown'};
  }
  function safeUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!/token|password|secret|api[_-]?key/i.test(u.search)?u.href:'';}catch{return '';}}
  function capsuleReport(capsule){return ['# '+capsule.key,'Local task capsule · review before sharing','Next: '+capsule.next,'Saved: '+capsule.updatedAt,...(capsule.repos||[]).map(repo=>'- '+repo.path+' | branch '+(repo.branch||'Detached HEAD')+' | base '+(repo.head||'Unborn HEAD')),'No logs, file contents, credentials or automatic branch switching.'].join('\n');}
  function scopedServices(items,folder,sets=[]){
    if(!folder||folder==='all')return items;
    if(folder.startsWith('set:')){const paths=new Set((sets.find(item=>item.name===folder.slice(4))?.paths||[]).map(keyOf));return items.filter(item=>paths.has(keyOf(item.path)));}
    const root=keyOf(folder).replace(/[\\/]+$/,'').replaceAll('\\','/')+'/';
    return items.filter(item=>{const path=keyOf(item.path).replaceAll('\\','/').replace(/\/+$/,'');return path===root.slice(0,-1)||path.startsWith(root);});
  }
  const helpers={ticketKey,matches,attention,remoteAttention,impact,proof,safeUrl,capsuleReport,scopedServices,providerRef,primaryViews,toolMatches};
  if(typeof module!=='undefined'){module.exports=helpers;return;}
  const F=window.GitDeckFleet;if(!F||typeof api!=='function')return;
  const {addPanel,table,row,mapLimit,query}=F;
  const records=new Map();let services=[];let store={capsules:[],recipes:[]};let activeKey='';let failureSelection=null;
  const stamp=value=>Number.isFinite(Date.parse(value||''))?new Date(value).toLocaleString():'Unknown';
  const button=(label,run,primary=false)=>{const node=el('button',primary?'primary':'',label);node.type='button';node.onclick=run;return node;};
  const input=(label,value='')=>{const node=el('input','workflow-input');node.type='search';node.placeholder=label;node.setAttribute('aria-label',label);node.value=value;return node;};
  const note=(host,text,bad=false)=>{host.textContent=text;host.classList.toggle('tone-warn',bad);};
  const action=(name,body)=>api('/api/action',{method:'POST',body:JSON.stringify({action:name,...body})});
  const link=(label,url)=>{const node=el('a','cockpit-link',label);const safe=safeUrl(url);if(safe){node.href=safe;node.target='_blank';node.rel='noopener noreferrer';}else{node.textContent=label+' (link unavailable)';}return node;};
  const open=(repo,tab='history')=>{document.getElementById('operations-close')?.click();return openWorkspace({path:repo.path,name:repo.name||repo.service||repo.path.split(/[\\/]/).pop()},tab,null);};
  function screen(panel,title,description){panel.classList.add('cockpit-panel');const head=el('header','cockpit-head');head.append(el('h2','',title),el('p','fleet-muted',description));panel.append(head);return head;}
  function grid(headers,rows){const wrap=el('div','cockpit-table-scroll');const node=table(headers);for(const cells of rows)node.append(row(cells));wrap.append(node);return wrap;}
  async function catalog(){services=(await api('/api/catalog')).services||[];return services;}
  async function tasks(){store=await api('/api/tasks');return store;}
  const scopeFor=folder=>scopedServices(services,folder,typeof readWorksets==='function'?readWorksets():[]);
  function selectedPaths(box){return [...box.querySelectorAll('input[type=checkbox]:checked')].map(node=>node.value);}
  async function repoPicker(host){await catalog();host.replaceChildren();for(const item of services){const label=el('label','cockpit-pick');const box=el('input');box.type='checkbox';box.value=item.path;box.disabled=!item.available;label.append(box,el('span','',item.service));label.title=item.path;host.append(label);}}

  function buildInbox(panel){
    screen(panel,t('Needs attention'),t('Repositories with something to do: conflicts, uncommitted files, commits to push or pull. Read from this computer; nothing is fetched.'));
    const toolbar=el('div','operations-toolbar'),folder=F.folderSelect(),search=input(t('Filter repositories or branches')),check=button(t('Check again'),load,true);toolbar.append(folder,search,check);
    const status=el('p','cockpit-status'),out=el('div');status.setAttribute('role','status');panel.append(toolbar,status,out);let values=[],serial=0;
    function draw(){const term=search.value.toLowerCase();const shown=values.filter(item=>[item.repo.service,item.repo.path,item.snapshot?.branch].join(' ').toLowerCase().includes(term)).map(item=>{const candidates=[...records.entries()].filter(([id])=>id.startsWith(keyOf(item.repo.path)+'|')).sort((a,b)=>Date.parse(b[1].checkedAt)-Date.parse(a[1].checkedAt));const record=candidates[0]?.[1];const local=attention(item.snapshot),remote=remoteAttention(item.snapshot,record);return {...item,hint:remote&&remote.rank<local.rank?remote:local,remote};}).filter(item=>item.hint.rank<5);shown.sort((a,b)=>a.hint.rank-b.hint.rank||a.repo.service.localeCompare(b.repo.service));out.replaceChildren();if(!shown.length){out.append(el('p','cockpit-empty',values.length?t('Nothing to do: every repository is committed, pushed and up to date.'):t('Checking…')));return;}out.append(grid(['Repository','Working branch','Next action','Checked'],shown.slice(0,100).map(item=>{const hint=item.hint;const run=()=>{if(hint.tab==='failure-lens'){failureSelection={path:item.repo.path,ref:hint.ref||item.snapshot.branch};showOperationsCenter('failure-lens');document.dispatchEvent(new Event('gitdeck-failure-selection'));}else if(hint.tab==='my-work')showOperationsCenter('my-work');else open(item.repo,hint.tab);};return [button(item.repo.service,run),item.snapshot?.branch||'Unknown',button(hint.label,run),stamp(item.snapshot?.checkedAt)+(item.remote?' · Remote snapshot, verify again':'')];})));if(shown.length>100)out.append(el('p','fleet-muted','Showing the first 100 actionable repositories. Filter to narrow the results.'));}
    async function load(){const request=++serial;check.disabled=true;note(status,'Checking registered repositories…');try{await catalog();const scoped=scopeFor(folder.value);const repos=scoped.slice(0,200);const results=await mapLimit(repos,4,async repo=>{try{return {repo,snapshot:(await api('/api/repo/task-snapshot?'+query({path:repo.path}))).snapshot};}catch(error){return {repo,error:error.message};}});if(request!==serial)return;values=results;draw();note(status,'Checked '+values.length+' repositories · '+values.filter(item=>item.error).length+' unavailable · '+new Date().toLocaleTimeString()+' · Local only'+(scoped.length>200?' · Scope limited to 200; use a workset.':''));}catch(error){if(request===serial)note(status,error.message,true);}finally{if(request===serial)check.disabled=false;}}
    search.oninput=draw;folder.onchange=()=>{serial++;values=[];check.disabled=false;load();};draw();
    // Local and read-only, so it runs as soon as the view opens.
    load();
  }

  function buildCockpit(panel,title=t('My work')){
    screen(panel,title,t('Type a ticket key to see its branches, commits, review and build in every repository. Local Git first; GitLab only when you ask.'));
    const toolbar=el('form','operations-toolbar'),folder=F.folderSelect(),key=input('Ticket key, for example PAY-123'),find=button('Find ticket',null,true);find.type='submit';toolbar.append(folder,key,find);
    const status=el('p','cockpit-status'),body=el('div','cockpit-body');status.setAttribute('role','status');panel.append(toolbar,status,body);let values=[],selected=null,serial=0;const selectedRefs=new Map();
    const invalidate=()=>{serial++;find.disabled=false;values=[];selected=null;selectedRefs.clear();body.replaceChildren(el('p','cockpit-empty','Find the ticket again to view current results.'));note(status,'Search changed. Old results cannot be used.');};key.oninput=invalidate;folder.onchange=invalidate;
    toolbar.onsubmit=async event=>{event.preventDefault();const wanted=key.value.trim().toUpperCase();if(!ticketKey(wanted)){note(status,'Use a ticket key such as PAY-123.',true);return;}const request=++serial;find.disabled=true;note(status,'Reading local branches and commits…');try{await catalog();const scoped=scopeFor(folder.value);const scope=scoped.slice(0,200);const found=await mapLimit(scope,4,async repo=>{try{const ticket=(await api('/api/repo/ticket?'+query({path:repo.path,key:wanted}))).ticket;return {repo,ticket};}catch(error){return {repo,error:error.message};}});if(request!==serial)return;activeKey=wanted;values=found.filter(item=>item.ticket&&(item.ticket.branches.length||item.ticket.commits.length));selected=values[0]||null;note(status,'Checked '+found.length+' repositories · '+values.length+' matches · '+found.filter(item=>item.error).length+' unavailable'+(scoped.length>200?' · First 200 only; narrow the workset.':''));draw(wanted,request);}catch(error){if(request===serial)note(status,error.message,true);}finally{if(request===serial)find.disabled=false;}};
    function branchOf(item){const branches=item.ticket.branches||[];return branches.find(branch=>branch.name===selectedRefs.get(keyOf(item.repo.path)))||branches.find(branch=>!branch.remote&&branch.name===item.ticket.current)||branches.find(branch=>!branch.remote)||branches[0]||null;}
    function draw(wanted,request){
      body.replaceChildren();if(!values.length){body.append(el('p','cockpit-empty','No ticket evidence in the checked local refs. Check the scope or Fetch to update remote refs.'));return;}
      const layout=el('div','cockpit-evidence-layout'),main=el('section'),detail=el('aside','cockpit-inspector');layout.append(main,detail);body.append(layout);
      const item=selected,record=records.get(keyOf(item.repo.path)+'|'+wanted)||{},branch=branchOf(item),summary=proof(branch,record.mrs,record.ci,record.observed);
      main.append(el('h3','cockpit-ticket-title',wanted));const trail=el('ol','cockpit-trail');for(const [label,value] of [['Code',values.length+' repositories'],['Review',summary.review],['Build',summary.build],['Environment',summary.environment]]){const part=el('li');part.append(el('strong','',label),el('span','',value));part.classList.toggle('cockpit-failed',value==='Failed');trail.append(part);}main.append(trail,el('h3','','Repository evidence'));
      main.append(grid(['Repository','Ticket branch','MR / review','Build','Environment'],values.map(value=>{const r=records.get(keyOf(value.repo.path)+'|'+wanted)||{};const p=proof(branchOf(value),r.mrs,r.ci,r.observed);const name=button(value.repo.service,()=>{selected=value;draw(wanted,request);});name.setAttribute('aria-pressed',String(selected===value));return [name,branchOf(value)?.name||'Commit evidence only',p.review,p.build,p.environment];})));
      main.append(el('p','fleet-muted','Read-only snapshots · Pipeline success is not deployment proof. Tags do not establish a build-to-image link.'));
      main.append(el('h3','','Recent ticket commits'));const commits=(item.ticket.commits||[]).slice(0,12);main.append(grid(['Commit','Description','Date'],commits.map(commit=>[String(commit.fullHash||commit.hash).slice(0,8),commit.subject,commit.date])));
      if(item.ticket.limited)main.append(el('p','tone-warn','Local ticket search is truncated (30 branches / 60 log candidates / 12 tags). Use Git history for the full list.'));
      if(summary.build==='Failed'){const alert=el('section','cockpit-attention');alert.append(el('h3','','Attention needed'),el('strong','','Build failed'),el('p','','The checked pipeline matches this ticket ref. Open its failed jobs; the cause is not yet established.'),button('Open failed check',()=>{failureSelection={path:item.repo.path,ref:providerRef(branch)};showOperationsCenter('failure-lens');document.dispatchEvent(new Event('gitdeck-failure-selection'));},true));detail.append(alert);}detail.append(el('h3','',item.repo.service),el('p','fleet-muted','Working on: '+item.ticket.current),el('p','','Ticket ref: '+(branch?.name||'Unknown')),button('Open workspace',()=>open(item.repo),true),button('Copy repository path',async()=>{try{await navigator.clipboard.writeText(item.repo.path);note(status,'Repository path copied.');}catch{note(status,'Clipboard unavailable.',true);}}));
      const refs=el('select','workflow-input');refs.setAttribute('aria-label','Ticket evidence branch');for(const value of item.ticket.branches||[])refs.append(new Option(value.name,value.name));refs.value=branch?.name||'';refs.disabled=!refs.options.length;refs.onchange=()=>{selectedRefs.set(keyOf(item.repo.path),refs.value);draw(wanted,++serial);};detail.append(refs);
      const remote=button('Check remote evidence',async()=>{remote.disabled=true;note(status,'Reading matching open MRs and branch pipeline…');const captured=item;
        const current={mrs:[],ci:null,checkedAt:new Date().toISOString(),errors:[]};
        try{const list=(await api('/api/repo/mrs?'+query({path:item.repo.path}))).mergeRequests||[];const found=list.filter(mr=>matches(mr.source,wanted)||matches(mr.title,wanted));current.limited=found.length>8||list.length>=50;current.mrs=await mapLimit(found.slice(0,8),2,async mr=>{try{return (await api('/api/repo/mr-readiness?'+query({path:item.repo.path,iid:mr.iid}))).readiness;}catch{return {...mr,approval:{status:'unknown'},sha:'',pipeline:'unknown'};}});}catch(error){current.errors.push(error.message);}
        if(branch)try{current.ci=(await api('/api/repo/ci?'+query({path:item.repo.path,ref:providerRef(branch)}))).ci;}catch(error){current.errors.push(error.message);}
        if(request!==serial||key.value.trim().toUpperCase()!==wanted)return;records.set(keyOf(captured.repo.path)+'|'+wanted,{...records.get(keyOf(captured.repo.path)+'|'+wanted),...current});note(status,current.errors.length?'Some remote evidence is unavailable; unknown states are shown.':'Remote evidence checked at '+stamp(current.checkedAt),Boolean(current.errors.length));draw(wanted,request);
      });detail.append(remote,el('small','catalog-stamp','Remote checked: '+stamp(record.checkedAt)));
      for(const mr of record.mrs||[])detail.append(link('MR !'+mr.iid+' · '+(mr.title||'Review'),mr.url));if(record.ci?.url)detail.append(link('Open pipeline',record.ci.url));
      if(record.limited)detail.append(el('p','tone-warn','Only the latest 50 open MRs and first 8 ticket matches were checked.'));
      for(const error of record.errors||[])detail.append(el('p','tone-warn',error));
      const envs=item.repo.environments||[];if(envs.length){const select=el('select','workflow-input');select.setAttribute('aria-label','Observed environment');for(const env of envs)select.append(new Option(env.env.toUpperCase(),env.env));const check=button('Check environment',async()=>{check.disabled=true;const targetEnv=select.value;select.disabled=true;const current={observed:null,envError:''};try{current.observed=(await api('/api/repo/observed-env?'+query({path:item.repo.path,env:targetEnv}))).observed;}catch(error){current.envError=error.message;}if(request!==serial)return;records.set(keyOf(item.repo.path)+'|'+wanted,{...records.get(keyOf(item.repo.path)+'|'+wanted),...current});draw(wanted,request);});detail.append(select,check);}else detail.append(el('p','fleet-muted','Environment not configured. Map an explicit Argo context in Systems.'));
      if(record.envError)detail.append(el('p','tone-warn',record.envError));
      if(record.observed){detail.append(el('h4','','Controller snapshot'),el('p','','Health: '+(record.observed.health||'Unknown')+' · Sync: '+(record.observed.sync||'Unknown')),el('p','catalog-path','Revision: '+([record.observed.revision,...(record.observed.revisions||[])].filter(Boolean).join(', ')||'Unknown')),el('small','catalog-stamp','Observed: '+stamp(record.observed.reconciledAt)));for(const image of record.observed.images||[])detail.append(el('code','catalog-image',image));detail.append(el('p','fleet-muted',summary.image));}
      detail.append(button('Inspect failure',()=>{failureSelection={path:item.repo.path,ref:providerRef(branch)};showOperationsCenter('failure-lens');document.dispatchEvent(new Event('gitdeck-failure-selection'));}),button('Save task capsule',async()=>{const views=captureViews();try{await action('capsule-save',{key:wanted,next:'review',paths:values.map(value=>value.repo.path),views:views.filter(view=>values.some(value=>value.repo.path===view.path))});note(status,'Capsule saved locally. Branches were not changed.');}catch(error){note(status,error.message,true);}}));
    }
  }

  function captureViews(){const repo=state.workspaceRepo;if(!repo)return [];const list=document.querySelector('.commit-list');return [{path:repo.path,tab:['history','changes','overview'].includes(state.workspaceTab)?state.workspaceTab:'history',commit:document.querySelector('.commit-row.selected')?.dataset.commit||'',file:document.querySelector('.commit-file-row.selected .commit-file-main')?.dataset.path||'',scroll:Math.round(list?.scrollTop||0)}];}
  function buildCapsules(panel){
    screen(panel,'Task capsules','Save repository bases and reading position, not file contents or logs. Resume never switches branches or restores files.');const toolbar=el('div','operations-toolbar'),key=input('Capsule ticket key',activeKey),next=el('select','workflow-input');next.setAttribute('aria-label','Next step');for(const value of ['review','test','push','request-review','check-environment'])next.append(new Option(value.replaceAll('-',' '),value));const picker=el('div','cockpit-picker'),status=el('p','cockpit-status'),out=el('div');const save=button('Save capsule',async()=>{const paths=selectedPaths(picker);save.disabled=true;try{await action('capsule-save',{key:key.value.trim().toUpperCase(),next:next.value,paths,views:captureViews().filter(view=>paths.includes(view.path))});await load();note(status,'Saved locally. Review exported paths before sharing.');}catch(error){note(status,error.message,true);}finally{save.disabled=false;}},true);toolbar.append(key,next,save,button('Refresh capsules',load));panel.append(toolbar,picker,status,out);repoPicker(picker).catch(error=>note(status,error.message,true));
    async function load(){try{await tasks();out.replaceChildren();for(const capsule of store.capsules){const section=el('section','cockpit-capsule');section.append(el('h3','',capsule.key),el('p','fleet-muted',stamp(capsule.updatedAt)+' · Next: '+capsule.next));const checks=el('div');
      section.append(button('Check saved bases',async()=>{checks.replaceChildren();const results=await mapLimit(capsule.repos,4,async repo=>{try{return {repo,snapshot:(await api('/api/repo/task-snapshot?'+query({path:repo.path}))).snapshot};}catch{return {repo};}});checks.append(grid(['Repository','Saved branch','Current branch','Base'],results.map(value=>[value.repo.path.split(/[\\/]/).pop(),value.repo.branch,value.snapshot?.branch||'Unavailable',value.snapshot?.head===value.repo.head?'Same base':'Changed / unknown'])));}),button('Review handoff',()=>{const dialog=releaseDialog('Review task handoff');const report=el('textarea','cockpit-report');report.value=capsuleReport(capsule);report.setAttribute('aria-label','Editable handoff');dialog.body.append(el('p','','This contains local paths and branch names. Remove sensitive identifiers before sharing. Nothing is sent to an AI or another person.'),report);dialog.actions.append(button('Copy reviewed handoff',async()=>{try{await navigator.clipboard.writeText(report.value);dialog.dialog.close();}catch{note(status,'Clipboard unavailable.',true);}}));}),button('Remove capsule',async()=>{if(!confirm('Remove this local capsule? Repository files will not be deleted.'))return;try{await action('capsule-remove',{id:capsule.id,expectedUpdatedAt:capsule.updatedAt});await load();}catch(error){note(status,error.message,true);}}));
      for(const repo of capsule.repos)section.append(button('Resume '+repo.path.split(/[\\/]/).pop(),async()=>{try{const current=(await api('/api/repo/task-snapshot?'+query({path:repo.path}))).snapshot;const view=capsule.views.find(value=>keyOf(value.path)===keyOf(repo.path));if(current.head!==repo.head||current.branch!==repo.branch){if(!confirm('The saved base or branch changed. Open the current workspace without switching branches?'))return;open(repo);return;}await open(repo,view?.tab||'history');if(view?.tab==='history')restoreReading(repo,view);}catch(error){note(status,error.message,true);}}));section.append(checks);out.append(section);}if(!store.capsules.length)out.append(el('p','cockpit-empty','No capsules yet. Select repositories and save a ticket.'));}catch(error){note(status,error.message,true);}}
    load();
  }
  function restoreReading(repo,view){let tries=0,selected=false;const timer=setInterval(()=>{if(keyOf(state.workspaceRepo?.path)!==keyOf(repo.path)||++tries>60){clearInterval(timer);return;}const target=[...document.querySelectorAll('.commit-row')].find(node=>node.dataset.commit===view.commit);if(!target)return;if(!selected){target.click();selected=true;const list=document.querySelector('.commit-list');if(list)list.scrollTop=view.scroll||0;}if(view.file){const file=[...document.querySelectorAll('.commit-file-main')].find(node=>node.dataset.path===view.file);if(!file)return;file.click();}clearInterval(timer);},100);}

  function buildImpact(panel){screen(panel,'Change impact','Reverse dependencies declared in Systems. Missing edges are unknown; this is not automatic test selection.');const select=el('select','workflow-input');select.setAttribute('aria-label','Changed service');const status=el('p','cockpit-status'),out=el('div');panel.append(select,status,out);catalog().then(()=>{for(const service of services)select.append(new Option(service.service,service.path));draw();}).catch(error=>note(status,error.message,true));select.onchange=draw;function draw(){const found=impact(services,select.value);out.replaceChildren(grid(['Affected service','Owner','System','Distance','Evidence'],found.map(item=>[button(item.service,()=>open(item)),item.owner||'Unknown',item.system||'Unknown',item.depth,item.evidence])));note(status,found.length+' declared consumers · Cycles deduplicated · Metadata may be incomplete.');out.append(el('p','fleet-muted','Review each affected service’s configured CI and tests. No test commands have been run.'));}}

  function buildRecipes(panel){screen(panel,'Fleet recipes','Preview → approve → status → diff summary → whitespace check. Tracked changes only; untracked contents are not checked. Read-only recipe v1; no staging, shell scripts, commits, pushes or MRs.');const picker=el('div','cockpit-picker'),status=el('p','cockpit-status'),out=el('div'),toolbar=el('div','operations-toolbar');const preview=button('Preview review plan',async()=>{preview.disabled=true;try{await action('recipe-preview',{recipe:'review-changes',paths:selectedPaths(picker)});await load();}catch(error){note(status,error.message,true);}finally{preview.disabled=false;}},true);toolbar.append(preview,button('Refresh plans',load));panel.append(toolbar,picker,status,out);repoPicker(picker).catch(error=>note(status,error.message,true));async function load(){try{await tasks();out.replaceChildren();for(const plan of store.recipes){const section=el('section','cockpit-capsule');section.append(el('h3','','Review changes · '+plan.state),el('small','catalog-stamp',stamp(plan.updatedAt)),grid(['Repository','Preview branch','Steps','Result'],plan.repos.map(repo=>[repo.path.split(/[\\/]/).pop(),repo.branch,repo.steps.map(step=>step.name+': '+step.state).join(' → '),[repo.state,repo.reason].filter(Boolean).join(' · ')])));const run=button(plan.state==='preview'?'Approve and run checks':'Resume unfinished checks',async()=>{if(!confirm('Run only the previewed read-only checks in '+plan.repos.length+' repositories? Changed repositories will be blocked. No commit or push.'))return;run.disabled=true;try{const answer=await action('recipe-run',{id:plan.id,expectedUpdatedAt:plan.updatedAt,approved:true});note(status,answer.message);await load();}catch(error){note(status,error.message,true);run.disabled=false;}},true);run.disabled=plan.state==='completed';section.append(run,button('Remove plan',async()=>{if(!confirm('Remove this recipe history entry? Repository files are kept.'))return;try{await action('recipe-remove',{id:plan.id,expectedUpdatedAt:plan.updatedAt});await load();}catch(error){note(status,error.message,true);}}));out.append(section);}if(!store.recipes.length)out.append(el('p','cockpit-empty','Choose up to 20 repositories and preview a plan.'));}catch(error){note(status,error.message,true);}}load();}

  function buildFailure(panel){screen(panel,'Failure lens','Failed jobs and pipeline SHA, not an inferred root cause. No raw logs or traces are collected.');const toolbar=el('div','operations-toolbar'),repo=el('select','workflow-input'),ref=input('Branch or tag for failure check'),check=button('Check failed jobs',load,true),status=el('p','cockpit-status'),out=el('div');repo.setAttribute('aria-label','Failure repository');toolbar.append(repo,ref,check);panel.append(toolbar,status,out);let serial=0;catalog().then(()=>{for(const item of services)repo.append(new Option(item.service,item.path));applySelection();}).catch(error=>note(status,error.message,true));const invalidate=()=>{serial++;check.disabled=false;out.replaceChildren();note(status,'Selection changed. Check again.');};repo.onchange=invalidate;ref.oninput=invalidate;function applySelection(){if(!failureSelection)return;repo.value=failureSelection.path;ref.value=failureSelection.ref;invalidate();}document.addEventListener('gitdeck-failure-selection',applySelection);async function load(){const request=++serial;check.disabled=true;out.replaceChildren();try{const failure=(await api('/api/repo/failure-lens?'+query({path:repo.value,ref:ref.value.trim()}))).failure;if(request!==serial)return;note(status,'Checked '+stamp(failure.checkedAt)+' · '+(failure.matchesLocalRef?'Pipeline SHA matches the known local ref':'Source match unknown / stale'));out.append(el('p','','Pipeline: '+failure.ci.status+' · SHA: '+(failure.ci.sha||'Unknown')),link('Open pipeline',failure.ci.url),grid(['Stage','Job','Status','Provider reason'],failure.jobs.map(job=>[job.stage,link(job.name,job.url),job.status,job.reason||'Not provided'])));if(!failure.jobs.length)out.append(el('p','','No failed/canceled/manual jobs in the returned results. This does not prove the pipeline or deployment succeeded.'));if(failure.limited)out.append(el('p','tone-warn','Only the first 100 jobs were read. Check GitLab for the full pipeline.'));out.append(el('p','fleet-muted','Open the provider job for logs. Log/trace correlation requires your instrumentation and is not assumed.'));}catch(error){if(request===serial)note(status,'Evidence unknown: '+error.message,true);}finally{if(request===serial)check.disabled=false;}}}

  addPanel('my-work',t('My work'),buildCockpit);addPanel('focus-inbox',t('Needs attention'),buildInbox);addPanel('capsules',t('Task capsules'),buildCapsules);addPanel('impact',t('Change impact'),buildImpact);addPanel('recipes',t('Fleet recipes'),buildRecipes);addPanel('failure-lens',t('Failure lens'),buildFailure);addPanel('release-proof',t('Release proof'),panel=>buildCockpit(panel,t('Release proof')));
  // All repositories is a primary destination, not a secondary health tool.
  const nav=document.querySelector('.operations-tabs'),modal=document.querySelector('.operations-modal');
  if(nav&&modal){
    modal.classList.add('cockpit-dashboard');
    const tabs=[...nav.querySelectorAll('[data-operations-view]')];
    const search=nav.querySelector('input'),mobile=nav.querySelector('select');
    const tools=el('details','cockpit-tools'),summary=el('summary','',t('More tools'));tools.append(summary);
    const primary=el('section','catalog-nav-group cockpit-primary');
    for(const id of primaryViews){const tab=tabs.find(node=>node.dataset.operationsView===id);if(tab){if(id==='fleet')tab.textContent=t('All repositories');if(id==='catalog')tab.textContent=t('Systems');primary.append(tab);}}
    for(const tab of tabs)if(!primary.contains(tab))tools.append(tab);
    const empty=el('p','cockpit-nav-empty',t('No matching tools. Try repository, CI or release.'));empty.hidden=true;empty.setAttribute('role','status');
    nav.replaceChildren(primary,tools,empty);if(search)nav.prepend(search);
    if(mobile){mobile.replaceChildren();for(const tab of [...primary.children,...tools.querySelectorAll('button')])mobile.append(new Option(tab.textContent,tab.dataset.operationsView));mobile.onchange=()=>tabs.find(tab=>tab.dataset.operationsView===mobile.value)?.click();nav.append(mobile);}
    const ordered=[...primary.children,...tools.querySelectorAll('button')];
    function filterTools(){const term=search?.value.trim()||'';for(const tab of tabs)tab.hidden=!toolMatches(tab.dataset.operationsView,tab.textContent,term);empty.hidden=tabs.some(tab=>!tab.hidden);primary.hidden=![...primary.children].some(tab=>!tab.hidden);tools.hidden=![...tools.querySelectorAll('button')].some(tab=>!tab.hidden);const active=tabs.find(tab=>tab.classList.contains('active'));tools.open=Boolean(term)||Boolean(active&&tools.contains(active));}
    function syncActive(){const active=tabs.find(tab=>tab.classList.contains('active'));if(active?.hidden&&search?.value){search.value='';filterTools();}for(const tab of tabs){if(tab===active)tab.setAttribute('aria-current','page');else tab.removeAttribute('aria-current');}if(active&&mobile)mobile.value=active.dataset.operationsView;if(active&&tools.contains(active))tools.open=true;}
    for(const tab of tabs)tab.addEventListener('click',syncActive);
    if(search)search.onkeydown=event=>{if(event.key!=='Enter')return;const target=ordered.find(tab=>!tab.hidden);if(target){event.preventDefault();target.click();target.focus();}};
    new MutationObserver(syncActive).observe(nav,{subtree:true,attributes:true,attributeFilter:['class']});syncActive();
    // Reopening the active view does not mutate its class, so synchronize explicitly.
    const baseSwitch=switchOperationsView;
    switchOperationsView=function(view){const result=baseSwitch(view);syncActive();return result;};
    if(search)search.oninput=filterTools;
  }
  window.GitDeckCockpit={...helpers,records};
  const dashboard=document.getElementById('dashboard-button');if(dashboard){dashboard.onclick=()=>showOperationsCenter('pending');dashboard.title=t('Pending work in every repository, plus All repositories, My work, Needs attention and Systems');}
})();
